/* eslint-disable import/prefer-default-export */

import {
  StyleSheet,
} from 'react-native';
import {
  PrimaryColor, SecondaryColor, White, LightGrey, DarkGrey,
} from '../../res/values/Styles';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: White,
    alignItems: 'center',
    justifyContent: 'space-evenly',
  },
  roomListcontainer: {
    flex: 1,
    backgroundColor: White,
    justifyContent: 'center',
  },
  buttonContainer: {
    flexDirection: 'row',
  },
  headerContainer: {
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
    height: 120,
  },
  searchButton: {
    alignItems: 'center',
    backgroundColor: White,
    borderColor: PrimaryColor,
    borderWidth: 2,
    padding: 10,
    margin: 15,
    borderRadius: 20,
    flexDirection: 'row',
  },
  buttonActive: {
    alignItems: 'center',
    backgroundColor: PrimaryColor,
    padding: 10,
    margin: 15,
    borderRadius: 20,
  },
  buttonInactive: {
    alignItems: 'center',
    backgroundColor: SecondaryColor,
    padding: 10,
    margin: 15,
    borderRadius: 20,
  },
  searchButtonText: {
    fontSize: 16,
    marginRight: 5,
    color: PrimaryColor,
    fontFamily: 'latoBold',
  },
  headerText: {
    fontSize: 40,
    color: PrimaryColor,
    fontFamily: 'montBold',
  },
  whiteText: {
    fontSize: 16,
    color: White,
    fontFamily: 'latoBold',
  },
  primaryText: {
    fontSize: 16,
    color: PrimaryColor,
    fontFamily: 'latoBold',
    alignSelf: 'center',
  },
  dateText: {
    minWidth: 135,
  },
  bookingIcon: {
    height: 20,
    width: 20,
    resizeMode: 'contain',
  },
  headers: {
    flex: 1,
    paddingTop: 15,
    paddingBottom: 15,
    flexDirection: 'row',
    justifyContent: 'space-between',
    borderColor: LightGrey,
    borderBottomWidth: 0.5,
  },
  sectionHeader: {
    fontSize: 16,
    flexGrow: 1,
    fontWeight: 'bold',
    fontFamily: 'latoBold',
    marginLeft: 10,
  },
  sectionHeaderIsFree: {
    flexGrow: 0,
    width: 200,
    marginLeft: 0,
  },
  item: {
    flexDirection: 'row',
    borderColor: LightGrey,
    borderBottomWidth: 0.5,
  },
  roomText: {
    flex: 1,
    fontSize: 16,
    fontFamily: 'latoLight',
    paddingTop: 15,
    paddingBottom: 15,
    marginLeft: 10,
  },
  time: {
    flexGrow: 0,
    width: 160,
    flexDirection: 'row',
    justifyContent: 'flex-start',
    paddingTop: 15,
    paddingBottom: 15,
  },
  bookingButton: {
    width: 40,
    flexGrow: 0,
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
  },
  timeText: {
    fontSize: 16,
    fontFamily: 'latoLight',
    width: 95,
    justifyContent: 'space-between',
  },
  noRoomsHeader: {
    fontSize: 20,
    fontWeight: 'bold',
    fontFamily: 'latoBold',
    alignSelf: 'center',
  },
  searchButtonActive: {
    alignItems: 'center',
    backgroundColor: White,
    borderColor: PrimaryColor,
    borderWidth: 2,
    padding: 10,
    margin: 15,
    borderRadius: 20,
    flexDirection: 'row',
  },
  searchButtonInActive: {
    alignItems: 'center',
    backgroundColor: White,
    borderColor: SecondaryColor,
    borderWidth: 2,
    padding: 10,
    margin: 15,
    borderRadius: 20,
    flexDirection: 'row',
  },
  inactiveText: {
    fontSize: 16,
    color: SecondaryColor,
    fontFamily: 'latoBold',
    alignSelf: 'center',
  },
  activeText: {
    fontSize: 16,
    color: PrimaryColor,
    fontFamily: 'latoBold',
    alignSelf: 'center',
  },
  text: {
    fontSize: 16,
    color: DarkGrey,
    alignSelf: 'flex-start',
  },
  errorText: {
    fontSize: 16,
    color: 'red',
    fontFamily: 'montBold',
    alignSelf: 'center',
  },
  successText: {
    fontSize: 20,
    color: PrimaryColor,
    fontFamily: 'montBold',
    alignSelf: 'center',
  },
  inputContainer: {
    borderColor: LightGrey,
    backgroundColor: '#FFFFFF',
    borderRadius: 30,
    borderWidth: 1,
    width: 250,
    height: 45,
    marginBottom: 20,
    flexDirection: 'row',
    alignItems: 'center',
  },
  inputs: {
    height: 45,
    marginLeft: 16,
    borderBottomColor: '#FFFFFF',
    flex: 1,
  },
  inputIcon: {
    width: 30,
    height: 30,
    marginLeft: 15,
    justifyContent: 'center',
  },
  loginButton: {
    backgroundColor: PrimaryColor,
  },
  loginText: {
    color: White,
  },
  loading: {
    position: 'absolute',
    left: 0,
    right: 0,
    top: 0,
    bottom: 0,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#F5FCFF88',
  },
});
